version: "3.9"

networks:
  microservice-network:
    name: microservice-network

services:

  config-server:
    build: ../config-server
    image: config-server:1.0
    networks:
      - microservice-network
    ports:
      - "8888:8888"
    environment:
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka

  eureka-server:
    build: ../eureka-server
    image: eureka-server:1.0
    networks:
      - microservice-network
    ports:
      - "8761:8761"

  api-gateway:
    build: ../api-gateway
    image: api-gateway:1.0
    networks:
      - microservice-network
    ports:
      - "9191:9191"
    environment:
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
      spring.cloud.config.uri: http://config-server:8888