version: "3.9"

networks:
  microservice-network:
    name: microservice-network

services:

#  config-server:
#    image: config-server:1.0
#    networks:
#      - microservice-network
#    ports:
#      - "8888:8888"

  eureka-server:
    image: eureka-server:1.0
    networks:
      - microservice-network
    ports:
      - "8761:8761"
#    depends_on:
#      - config-server

  api-gateway:
    image: api-gateway:1.0
    networks:
      - microservice-network
    ports:
      - "9191:9191"
    depends_on:
#      - config-server
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
#      SPRING_CLOUD_CONFIG_URI: http://config-server:8888

