version: "3.9"

networks:
  microservice-network:
    name: microservice-network

services:

  config-server:
    container_name: config-server
    build: ../config-server
    image: config-server:1.0
    networks:
      - microservice-network
    ports:
      - "8888:8888"
    environment:
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka

  eureka-server:
    container_name: eureka-server
    build: ../eureka-server
    image: eureka-server:1.0
    networks:
      - microservice-network
    ports:
      - "8761:8761"

  api-gateway:
    container_name: api-gateway
    build: ../api-gateway
    image: api-gateway:1.0
    networks:
      - microservice-network
    ports:
      - "9191:9191"
    environment:
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
      spring.cloud.config.uri: http://config-server:8888

  mysql-container:
    container_name: mysql-container
    image: mysql:latest
    networks:
      - microservice-network
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: db_microservice_a
    entrypoint:
      sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS db_microservice_a;
        CREATE DATABASE IF NOT EXISTS db_microservice_b;'
        > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_unicode_ci
      "
    volumes:
    - /var/lib/mysql

  microservice-a:
    container_name: microservice-a
    build: ../microservice-a
    image: microservice-a:1.0
    networks:
      - microservice-network
    ports:
      - "9001:9001"
    depends_on:
      - mysql-container
    environment:
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
      spring.cloud.config.uri: http://config-server:8888
      spring.datasource.url: jdbc:mysql://mysql-container:3306/db_microservice_a?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC

  microservice-b:
    container_name: microservice-b
    build: ../microservice-b
    image: microservice-b:1.0
    networks:
      - microservice-network
    ports:
      - "9002:9002"
    depends_on:
      - mysql-container
    environment:
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
      spring.cloud.config.uri: http://config-server:8888
      spring.datasource.url: jdbc:mysql://mysql-container:3306/db_microservice_b?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC

#volumes:
# - my-datavolume
